version: '2.4'
services:

  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - TZ=America/Bogota
      - PUID=1003
      - PGID=1003
    network_mode: host
    volumes:
      - ~/plex/database:/config
      - ~/plex/transcode/temp:/transcode
     # - ~/plex/media:/data
      - media:/data

volumes:
  media:
    driver: local
    driver_opts:
      type: cifs
      o: "username=zaramando,password=m4nd1,vers=3.0,uid=1003,gid=1003"
      device: //192.168.1.31/zaramando/DATOS2/plex/media
